### ISSUE TITLE
Post hashes to blockchain [$2,100]

### ISSUE THREAD

**Issue by xloem** [xloem/openrealrecord#1]
The program must be able to post to the bitcoin blockchain a cryptographic hash of the entire tree of feeds.  EDIT: this is similar to a trusted timestamp, but must be collision resistant to prevent data alteration.  This hash will hopefully prove that the contents are correct and were produced prior to the block publication time.  The user will of course need to provide a wallet filled with coins so that the software may post these hashes.  The software may be tested without financial investment by using a testnet.

It is not necessary to read all the comments to pursue this issue.  I began pursuing this on the [wip](https://github.com/xloem/openrealrecord/tree/wip) branch using bcoin.  That could be used as a base; the most important bit is the addition of modularity to allow different components such as this one.

[javascript-opentimestamps](https://github.com/opentimestamps/javascript-opentimestamps) was proposed as the backend for a solution.  Although this would be a completely fine solution that would close this issue, ideally it would be better to connect directly to a wallet interface, as opentimestamps relies on the behavior of a number of third-party servers by default.  The functionality those servers provide is already present in the stream trees of this project.

An ethereum smart contract has been suggested, but the implementer found it quite hard to construct.  

Thank you for reading.

**Comment by xloem** [comment]
I started some work on this in the [wip](https://github.com/xloem/openrealrecord/tree/wip) branch.  I added a dependency on bcoin and began coding a module to post tip hashes to the feed stream tree.

Tip hashes are important, but what is more relevant would be streaming the transaction and block id where the last verifiable hash is posted.  The process running this would need a wallet filled with some coins.

The modularity component is important.  We'll want to have separate modules for each different kind of stream.

**Comment by pmg1991** [comment]
You could use existing open source https://github.com/opentimestamps/javascript-opentimestamps for this.

**Comment by xloem** [comment]
@pmg1991 Thanks for looking at this.  That sounds great, but it's hard to find in the javascript-opentimestamps code where the timestamp is actually posted to a blockchain.  If the library relies only on 3rd party servers it would seem insufficient to me, although I note that they have accepted every pull request submitted so far.

**Comment by pmg1991** [comment]
https://github.com/opentimestamps/python-opentimestamps/blob/master/opentimestamps/bitcoin.py this is what you are looking for.  https://github.com/opentimestamps/opentimestamps-server. Code is divided in 3 projects client , server and core.

**Comment by xloem** [comment]
The opentimestamps solution as-is seems imperfect to me, partly because the user of openrealrecord would have to run two auxiliary services to be decentralized (both calendar server and the blockchain node) rather than just one, but mostly because the additional auxiliary service is in python rather than javascript; it seems to me it would be much more cumbersome to bundle it in automatically.

However, I'd totally accept an opentimestamps-based PR to close this bug.  Anything that works !

- Note that opentimestamps produces a document describing the timestamp; these documents should obviously be streamed out by the module producing the timestamps, so other users can access them.  
- The verification step would need to ensure the data is actually in the blockchain via a decentralized process, which it looks like opentimestamps provides for.
- It looks like opentimestamps uses sha256 hashes by default.  These are probably sufficient for now, but it would be better to use blake2b or keccak.

**Comment by yuriy-yarosh** [comment]
> Anything that works !

Ok, I'll do it.

**Comment by xloem** [comment]
@yuriy-yarosh @pmg1991 I opened https://github.com/opentimestamps/javascript-opentimestamps/issues/22 regarding the hash selection.  Peter Todd said that verifying content (rather than just time) is not a supported use of opentimestamps, although perhaps I was too disagreeable.

It's important that these hashes verify the content as well as the time.

**Comment by xloem** [comment]
@petertodd thanks for the link!  I was unaware of single-use-seals.  They seem super useful, and I want to think of ways to use them.
We're trying to prove the integrity of data that is already present at the time of commitment, though.  Don't you think a single use seal would be overkill for this?  I really thought this was what trusted timestamps were for.

**Comment by yuriy-yarosh** [comment]
> Don't you think a single use seal would be overkill for this?

@xloem ethereum smart contracts based implementation should be simple enough.
It would be nicer to create some browser plugin like metamask.

I do agree with @petertodd it seams to me that OpenTimeStamps is a bit insufficient for OpenRealRecord use case and solves different purposes.

**Comment by petertodd** [comment]
I can't recommend Ethereum for this, as it's become extremely difficult for anyone to run a proper Ethereum full node.

**Comment by yuriy-yarosh** [comment]
> to run a proper Ethereum full node

I'm not suggesting running an eth hardfork, just publishing a dapp.
It's a nobrainer, as for me, personally, because it's possible to establish a BTC relay, possibly any other crypto too.

@petertodd I don't really think that there are any viable alternatives right now.
Folks who run hypercore nodes might consider running an eth node too.

And ofc you could put an ETH node with some hypercore inside an EOS node (and remember those old xzibit memes :suspect:).

@xloem what do you think about a self-sustainable ETH based dapp, where stream viewers could pay some fees for the distributed nodes resource consumption, so the network itself could become self-sustainable ?

**Comment by petertodd** [comment]
@yuriy-yarosh Doing nothing is an option that takes a lot less work, involves approximately as much trust, and is much less misleading to the general public.

**Comment by petertodd** [comment]
@yuriy-yarosh I mean, to be clear, without a full node end users won't know if they actually have the complete set of state commitments to any external thing committed to within ethereum; they'll be trusting others to tell them that. Given how hard it is to run a full ETH node, that list of others is now very small.

**Comment by xloem** [comment]
> what do you think about a self-sustainable ETH based dapp, where stream viewers could pay some fees for the distributed nodes resource consumption, so the network itself could become self-sustainable ?

@yuriy-yarosh that sounds fantastic

Note that all the core implementation I'm really asking for to close off this issue is nodejs code that (1) calls out to a local running bitcoin node and sends a transaction using a user-provided wallet that includes the rootsHash from the checkpoint, (2) once the tx is in the blockchain, streams out enough information for other clients to verify it independently, and (3) repeats the behavior.  The purpose is of course to give a strong upper bound on the end time of chunks of the data, and to show that the database has not been changed.

I don't agree with petertodd's apparent opinion that if there is some problem, it should not be done.  Some problem can be found in anything.  It should be done with the problem documented.  I personally feel the bitcoin blockchain is more resilient than ethereum ... simply because ethereum has resolved to switch to proof-of-stake before resolving how to implement it properly, which is weird.  But anything that works !  And I love the idea of the ethereum network keeping the streams alive itself.

**Comment by yuriy-yarosh** [comment]
It's quite hard to make a viable Ethereum contract, and it turned out to be a mess, because there are many broken and snatchable ones in the wild. I'm considering implementing some Ethereum contract analyzing service to formally prove contracts viability...

Anyway, it's a WIP, I'd like to discuss some details privately.

**Comment by xloem** [comment]
@yuriy-yarosh feel free to e-mail 0xloem@gmail.com ; I might reply with some delay.

**Comment by lucasa** [comment]
So, could the user pay some eth to write the record to the blockchain?
Is this a viable way?

**Comment by xloem** [comment]
@lucasa that is correct; although I would prefer the bitcoin blockchain to ethereum, really it would use a general interface so code could be written for either

**Comment by yuriy-yarosh** [comment]
@xloem you'll need smart contracts to manage the respective data, although it's not that hard to manage few extra crypto exchanges inside eth contracts.

I've got some spare time this weekend, hope will finish this.
p.s. you haven't replied to my mail.

**Comment by xloem** [comment]
To clarify for others, there is no need for smart contracts in resolving this issue.

I do see how effective use of smart contracts could be a great benefit, but maybe thay should be a separate issue, as it is a very different addition specific for the ethereum network.

**Comment by xloem** [comment]
@yuriy-yarosh I inferred from https://github.com/xloem/openrealrecord/issues/8#issuecomment-392362447 that you were no longer working on this.  There have been no commits to your fork at https://github.com/yuriy-yarosh/openrealrecord and the date you listed you would be completed by at https://www.bountysource.com/issues/58359678-post-hashes-to-blockchain is in the past.  Any updates?

I got your e-mail but it's hard to craft a reply specifically.  If you can show great work that creates forward progress, I'm happy to compensate in whatever means you prefer.

**Comment by Steve132** [comment]
So I can handle this and will gladly recieve the bounty, and I understand exactly what you want.   

However, I'm curious about a couple things:

1) Is this supposed to be inside the client or the server?   

2) Are there more details about the api and what details are to be hashed?  Its a bit tough to suss out exactly what the specification is for what you want. 

It shouldn't be hard.  Email me or talk to me here.

**Comment by xloem** [comment]
@Steve132 , thank you for your comment.

1. The client and the server are basically the same thing with hyperdb, but I guess you could say the servers are the nodes that are authorized to write to the shared database and stay running, whereas clients just download the bits of the database they need and never publish anything.  In that sense, this would be inside a server process.  It would stay alive and publish updates to the database for others to verify.

2.  Openrealrecord streams a tree of updates, where each new tree head includes a hash of all previous roots.  Hence, the last set of roots hashes has a unique hash that should be able to be used to verify all content.  This hash should be posted to the blockchain, and a reference to that post posted to the shared openrealrecord database.

I'm partly looking for somebody smart to sort out a good specification and API.  But I welcome you to use what I started in the wip and inuse branches.  I started work but cannot continue myself at the moment.  I'm quite happy to answer any specific questions about the source or hyperdb, but if you have the time to review it in depth it could be faster as I'm not always around.  I'm looking for any solution that is modular, maintains all the advertised goals, still supports realtime streaming, and is clear to review.  One could just add some code to the modules added in the wip branch to post hashes using bcoin.

I'm sorry i haven't posted the specific API functions.  I'll try to get back to this later and link to the specific functions to get the roots hashes and post an update to hyperdb, perhaps in a few days.  They're used in the CLI script in pipe mode.

**Comment by Steve132** [comment]
So I've looked over the code and now I'm familiar with how hyperstream works.  I'm confident I can do what you need.  There's some details I want to ask you though and some offline spec conversations.  Can you send me an email?  Thanks.

**Comment by 72Zn** [comment]
here is what you need: https://originstamp.org

**Comment by xloem** [comment]
@72Zn thanks, but let’s use a solution that does not require trusting a 3rd-party server.

**Comment by SunDawning** [comment]
For four months, I have been posting my own git commit and hash of the file to the blockchain [Steemit](https://steemit.com/cn/@sundawning/sundawning). Is this the way you want?

**Comment by amingilani** [comment]
Hi @xloem, I just ran into this bounty on bounty-source and sounds like definitely something I can do. It appears as though you want to prove the existence of something by embedding its hash in the blockchain.

This is something I can do and will be very interested in doing. I make the implementation in both Ethereum or Bitcoin, however, I have a few questions to talk over. Would you be available on Gitter?

We can communicate asynchronously.

**Comment by xloem** [comment]
@amingilani I invited you to https://gitter.im/openrealrecord/Lobby .  I think @Steve132 is also evaluating pursuing this.  Sorry for my delay; didn't notice your comment until now.

**Comment by amingilani** [comment]
That's fine. I guess it's a race to the finish line ;)

**Comment by freemanjackal** [comment]
can I join this right? I just need to understand the code, it is what will take most time

**Comment by bookmoons** [comment]
I have [an implementation](https://github.com/bookmoons/openrealrecord/tree/bookmoons/blockchain) working against an in memory `regtest` chain. There's no meaningful output but it's possible to run the tests:

```shell
git clone -b bookmoons/blockchain https://github.com/bookmoons/openrealrecord.git
cd openrealrecord
npm install
npm run test-mul
```

It does roughly this. Watch for checkpoints on the stream. For each checkpoint:
1) Package into a binary message. An `OP_RETURN` transaction has capacity 40 bytes. The hash seems to be 32 bytes. That leaves 8 bytes for a label. Tentatively prefixing with ASCII `ORRecord`, exactly 8 bytes.
2) Publish to the chain in an `OP_RETURN` transaction. Wait for confirmation.
3) Write a reference to that transaction to an ancillary feed in the stream namesapce, `checkpub/bitcoin`. Checkpub for checkpoint publication. I have this message defined in the protobuf schema. It stores the hash and the txid.

Working toward some testnet trials soon.

**Comment by bookmoons** [comment]
Finally got a testnet node synced. Successful trial here:
https://live.blockcypher.com/btc-testnet/tx/132bd319c1e93b9f8b9427ec067a4d42994118e0129f2f6eaea287f233ce6622/

At the top it shows the data in hex. ASCII `ORRecord` is hex `4f 52 52 65 63 6f 72 64`, visible at the front there.

Will package this up soon and submit a patch. I see there's a commit comment too, I'm just seeing it now. Will think about that respond.

**Comment by xloem** [comment]
@bookmoons , feel free to claim this bounty even though the PR is not yet merged
