### ISSUE TITLE
TypeScript Port [$350]

### ISSUE THREAD

**Issue by yuriy-yarosh** [xloem/openrealrecord#8]
We'll probably need a TypeScript port to make this project a bit more maintainable.
Typings would improve development XP and would help to reduce the amount of some simplest errors.

Flow is not a good option because it's a bit faulty and has upredictable release schedule - facebook can and will make broken Flow releases.

PureScript / ClojureScript / Scala.js / Kotlin are not that widespread, although there is some benefit in using clojurescript to reduce the amount of codebase.

**Comment by yuriy-yarosh** [comment]
> Could you do this with sequential pull requests

Sure.

> What's the plan for integration with hypercore and hyperdb ?

I could provide the respective typings, and/or could port hypercore/hyperdb to TypeScript at some point.

As for me, personally, the biggest downside of TypeScript is that they haven't implemented [Variadic Kinds](https://github.com/Microsoft/TypeScript/issues/5453) in almost two years, which makes TypeScript typings for functional libs a bit obscured. [FantasyLand](https://github.com/fantasyland/fantasy-land) / [StaticLand](https://github.com/rpominov/static-land) specs are a bump with TypeScript, ramda/lodash-fp typings are inconsistent too.

**Comment by yuriy-yarosh** [comment]
@xloem, well... both @mafintosh and @pfrazee had proven to be jerks.

```
> @yuriy-yarosh What do you think is inconsistent?

@emilbayes 

• poor naming
For instance, [Feed constructor](https://github.com/mafintosh/hypercore/blob/master/index.js#L27), `function Feed (createStorage, key, opts) {` could've been `function Feed (name, key, opts) {`
and with a static method like `feedWith = (builder) => { /* some magic*/ }` it's much simpler to distinguish instantiation methods.

This `onwrite` [hook](https://github.com/mafintosh/hypercore/blob/master/index.js#L66), which I suppose was used for testing purposes, but haven't been removed for some reason, should've been removed or replaced. And there are plenty of mocking libraries for that.

There are way too many options in the Feed constructor itself, some of them are redundant for no reason. For example there's `opts.secretKey` [here](https://github.com/mafintosh/hypercore/blob/master/index.js#L45) and another `opts. storeSecretKey ` [over here](https://github.com/mafintosh/hypercore/blob/master/index.js#L72) some reason, I don't really get the point of these due to poor naming.

`ready` [method](https://github.com/mafintosh/hypercore/blob/master/index.js#L139) should've been named `onReady`

`undownload` [here](https://github.com/mafintosh/hypercore/blob/master/index.js#L326), really ? It's not a suitable name for a cancelation method. Anyway, cancelable streams, with a bit of FRP, should've been way more convenient.

• default parameters handling
Well, there's a convention throughout your code like `(parameters, opts, callback)`, but there are plenty of methods that don't need any opts but you're passing 'em anyway and defaulting to `{}` for no particular reason, which causes some confusion. [proof](https://github.com/mafintosh/hypercore/blob/master/index.js#L356) [seek](https://github.com/mafintosh/hypercore/blob/master/index.js#L525) [head](https://github.com/mafintosh/hypercore/blob/master/index.js#L887).

• inconsistent opts handling
There are few methods [get](https://github.com/mafintosh/hypercore/blob/master/index.js#L897) where it's really hard to distinguish between method parameter and an opt, and they've should've been merged, I suppose.

• inconsistent interfaces
For instance, you're accepting a range object `{start: 0, end: 1}` in , but in [downloaded](https://github.com/mafintosh/hypercore/blob/master/index.js#L877) and [has](https://github.com/mafintosh/hypercore/blob/master/index.js#L881) methods you're using method parameters instead.

You might pretend like it's nothing... well, add some [Code Climate](https://codeclimate.com/) and see for yourself.

@emilbayes nowadays, most of OpenSource projects out there, are in fact a pile of crap. I'm not saying that you guys are bad at developing things, it's just bad that you're unable to withstand even a small amount of constructive proposals due to personal cognitive biases and compensational needs. Making even a small amount of critics a personal matter is just showing your unwillingness of improvement. If you've got your personal matter, which can't be disclosed, involved - there's always a room for a private, brutally honest talk.

We've got a pile of crap to grow a garden... and you can't do that without accepting some refinement methods. And of course everything is subjective, and I've got my own biases, so, I'm here to discuss, not to argue. 

If you've wanted to establish some conventions - go for some eslint-rules ftw. It's just a yet another proof of [Ikea effect](https://en.wikipedia.org/wiki/IKEA_effect), [broken windows theory](https://en.wikipedia.org/wiki/Broken_windows_theory) and [complaint driven development](https://blog.codinghorror.com/complaint-driven-development/).

You could've replace your `(opts={}, cb)` with some mongo-like `optional callback` convention: if callback is being passed - use it, if there's none - just return a promise. `opts` are simply redundant and unnecessary.

There's just way to much complexity for such simple code, it could be reduced to improve long term support and overall project's QA.
```

And, ofc, I've got a perfect and reasonable reply:

![reply](https://habrastorage.org/webt/ra/3l/lu/ra3llur5-fppstd7_ouohejl67w.png)

**Comment by xloem** [comment]
@yuriy-yarosh, hypercore is the only software I've found that will provide sparse binary streaming data all signed with a single hash.  Do you know of anything else?

I'm sorry you had this interaction with one of the other contributers.  It would be great if you could assume that people are trying to help, even when they respond this way.  It sounds like he doesn't know you well, and actually thinks you are trying to hurt that project, so is interpreting your words from that assumption.

People tend to respond poorly when met with criticism with no work to help the situation.  It's maybe a good rule of thumb to contribute a little more than you complain.  Of course, we all get impatient and frustrated, so it's also good to put energy where you enjoy putting it.

Open source projects are mostly written in people's spare time, when they feel like it.  There is generally very little funding, and often things are hacked together imperfectly to make the best use of time and energy, under the assumption that others who care will have more time to fix it themselves.

I agree that there are some issues with hypercore and hyperdb, especially in the area of documentation.  In other areas, I've assumed hypercore hasn't used many javascript features because it seems to be targeting a very old release of node.  In general, I've had to explore the source, ask one of the developers, or look at some other projects that use the code, to figure out how to make effective use of the library.  And I feel guilty about this, because I should have been using the time to add to the documentation, so that future users wouldn't have to do the same thing.  There are some TODO's in openrealrecord's source regarding these kind of things.

Do you have any ideas to improve the situation?

Are you still interested in working on this, or the other bounty item?

**Comment by yuriy-yarosh** [comment]
> hypercore is the only software I've found that will provide sparse binary streaming data all signed with a single hash. Do you know of anything else?

Nope, but it's all merkle trees here and there, it's possible to implement some custom protocol at some point. I've got a nasty story with Adobe and rtmfp... and some lawsuits. I personally prefer developing stuff from scratch, so it's possible to polish things and control long-term risks.

> It's maybe a good rule of thumb to contribute a little more than you complain. 

It's just that I'm familiar with psychological aspects of such rule.

> Open source projects are mostly written in people's spare time, when they feel like it. 

Understandable, I've been developing provable programming language and a set of compiler tools, which will be published as a set OpenSource projects. It's actually possible to get a decent monetization out of an open source project, but it's quite hard and involves lots of enterprise grade politics / hypocrisy. It's hard to reinvent things when everyone chasing for profits.

> I've assumed hypercore hasn't used many javascript features because it seems to be targeting a very old release of node.

Well, they could've been polyfiled with some babel-env, for instance, and Babel7 has some support of both TypeScript and Flow, with minor fixable issues. There are some solutions for that problem, and they are proven to be viable in most cases.

>  In general, I've had to explore the source, ask one of the developers, or look at some other projects that use the code, to figure out how to make effective use of the library. 

Nah, I'm not blaming, it's just pretty common nowadays.

> Do you have any ideas to improve the situation?

• add some babel-env and modern day javascript features to reduce the boilerplate and fix the inconsistencies 
• add some TypeScript with Babel7
• fix few Babel7 issues and add some Variadic Kinds support to TypeScript
• use some cancelable streams with FRP to reduce the amount of codebase and improve maintainability
• make it google protobuf compliant and drop protocol-buffers
• profile crap out of it and implement flame graphs to identify the week spots with further optimizations via FFI with Rust/C and some minor SIMD intrinsics if needed (AVX2 usage could speed up I/O drastically)

> Are you still interested in working on this, or the other bounty item?

I'm interested in recieving a small bounty for this one, and I'm willing and able to improve existing hypercore codebase. It's not a huge or complicated project, so I should be fine.

**Comment by xloem** [comment]
hey @yuriy-yarosh 

> Nope, but it's all merkle trees here and there, it's possible to implement some custom protocol at some point. I've got a nasty story with Adobe and rtmfp... and some lawsuits. I personally prefer developing stuff from scratch, so it's possible to polish things and control long-term risks.

If you were able to do this project better from scratch (meeting all the goals listed in the summary + "realtime" which I forgot to include) that would be incredible.  I don't have the time for that, so I was very excited to find hypercore.  The protocol hypercore follows is implementation-agnostic, so it's not required to stick with the hypercore library itself, either: see https://www.datprotocol.com/ .  However, hyperdb and hypercore are MIT licensed, so there shouldn't be any legal problems, although IANAL.
 
> > It's maybe a good rule of thumb to contribute a little more than you complain.
> 
> It's just that I'm familiar with psychological aspects of such rule.

It's sounds like your connection with that concept has not been pleasant, and I'm so sorry that has happened to you.  I'm not sure what you specifically mean here, but I'm not saying to not do something when things are wrong -- I guess I'm just saying that communities have to defend themselves, and one approach to garnering trust is contribution.  There are probably other approaches too.  The hypercore devs have made it clear elsewhere that they don't have the time to make everything perfect yet, so we'd need to do more than just mentioning issues to get them resolved soon.

I've put a couple bounties on hypercore/hyperdb issues.  One was filled with not amazing quality (took a lot of review), the other has just stagnated ( https://www.bountysource.com/issues/54022449-to-prevent-mutation-of-history-use-merkle-root-hashes-in-addition-to-sequence-numbers ).  mafintosh has not replied to it, but I could talk to him on irc until he does.  The thing is, I'm not really sure how to actually get more quality work-hours happening with the few hours I have myself.  The blockchain issue on this project is kind of my next experiment, but I will likely just do that work myself soon.

> > Do you have any ideas to improve the situation?
> 
> • add some babel-env and modern day javascript features to reduce the boilerplate and fix the inconsistencies
> • add some TypeScript with Babel7
> • fix few Babel7 issues and add some Variadic Kinds support to TypeScript
> • use some cancelable streams with FRP to reduce the amount of codebase and improve maintainability
> • make it google protobuf compliant and drop protocol-buffers
> • profile crap out of it and implement flame graphs to identify the weak spots with further optimizations via FFI with Rust/C and some minor SIMD intrinsics if needed (AVX2 usage could speed up I/O drastically)

If you could make hypercore really strong, I think it would be a great effort.  If you made a fork and added a branch for each of those changes, we could optionally work with your fork while getting the changes to be something that upstream would be happy to merge in.  We can likely find a way to work with the devs, as long as we listen to their requests and needs.

**Comment by BrinaryG** [comment]
Hi

Is the goal here to convert the openrealrecord repo to Typescript? Is that what is required to complete the bounty?

Thanks

**Comment by BrinaryG** [comment]
Hey is anyone able to take a look at the PR?

**Comment by cyberhck** [comment]
I guess that's a WIP, I'd add a lot of linting, and I added a comment (I'm not sure about that, have a look)

**Comment by BrinaryG** [comment]
@cyberhck 

I have resolved the issue in your comment.

I think this PR is still a WIP I didnt want to dictate style/linting and I am really looking for some feedback on whether or not this is the direction everyone imagined this conversion to TS going.

Thank you for taking a look.

**Comment by cyberhck** [comment]
Yes, it's a right call that you didn't want to add linting that is totally a maintainer's call, linting would be a good addition, especially if it's very very strict. If maintainer wants, I'd be glad to suggest some rules (by some I mean a lot) (or maybe even a new issue for that would be a way to go)

Since all the tests are passing, I think next step would be to clean stuff up and wait for maintainer's approval. :slightly_smiling_face:

**Comment by xloem** [comment]
Hey all, there are a couple PRs open that appear good at first glance.  I haven't found the capacity to fully review them and may not for some time, but I'm closing this issue so that somebody can claim the bounty if they like.  @sahalsaad

**Comment by sahalsaad** [comment]
@xloem thanks. Feel free to comment the PR when you have free time. I'll fix it.
